privcount/privcount

.gitignore, privcount/data_collector.py, privcount/protocol.py, privcount/share_keeper.py, privcount/tally_server.py
A squashed version of "Add dc last event" with the same content as https://github.com/privcount/privcount/pull/25
=> Add dc last event squashed

privcount/tally_server.py, test/README.markdown, test/config.yaml, test/run_test.sh
Closes #7, see the description on that ticket
=> Better self test v3

.gitignore, privcount/data_collector.py, privcount/tally_server.py, privcount/util.py, test/test_format_time.py
An updated branch with clearer "expected collection end time" messages
=> Status message times v2

.gitignore, privcount/data_collector.py, privcount/inject.py, privcount/share_keeper.py, privcount/tally_server.py, privcount/util.py, test/test_format_time.py
Refactor out a lot of common code used for normalising paths into util.normalise_path
Normalise more paths.
Improve results file path normalisation and joining.
Based on merge request #32 (better status messages), because there are merge conflicts with the util imports.
Please don't merge this unless you're happy with both this and #32.
=> Better paths

README.markdown, privcount/data_collector.py, privcount/plot.py, privcount/protocol.py, privcount/share_keeper.py, privcount/tally_server.py, privcount/util.py, test/README.markdown, test/config.yaml, test/run_test.sh, test/test_counters.py, test/test_format_time.py, test/test_keyed_random.py, test/test_tor_ctl_event.py
Addresses many of the issues in 0.2.0 affecting counters, blinding, and q.
See per-commit messages for details.
=> Better counters

privcount/protocol.py
Fix two missing changes on #56 - importing os._exit, and a comment reflow.
=> Fail on error

privcount/util.py, requirements.txt, test/run_test.sh
Requires cryptography >= 1.4.
Closes #46
=> Encrypt and decrypt using SHA256 for padding, rather than SHA1

README.markdown, privcount/util.py
Also expand the install troubleshooting section in the README.
Closes #90.
=> PrivCount's SHA256 RSA padding requires OpenSSL 1.0.2

privcount/util.py, test/test_encryption.py
Improve encoding / decoding tests.
Relax type rules.
Improve counter input sanitisation.
Closes #79 and #80.
=> Use JSON for network communication

test/README.markdown, test/run_test.sh
=> Source the venv before running tests

privcount/data_collector.py, privcount/statistics_noise.py, test/counters.bins.yaml, test/counters.noise.yaml, test/counters.sigmas.yaml
=> Update CircuitLifeTime counters based on state of activeness

privcount/counter.py, privcount/data_collector.py, privcount/node.py, privcount/share_keeper.py, privcount/tally_server.py, test/config.yaml, test/run_test.sh
=> Fix enforced delay

test/test_tor_ctl_event.py
=> Make test_tor_ctl_port.py directly executable

privcount/log.py
=> Add imports used in log_error

.gitignore, privcount/protocol.py, test/run_test.sh
Closes #155
(Sorry, @robgjansen, this conflicts with #19.)
=> Output unexpected log messages at the end of integration testing

doc/TorBranch.markdown, doc/TorEvents.markdown
=> Event Doc (Revision 4)

doc/CounterChecks.markdown
=> Document counter sanity checks and enforced delays

privcount/inject.py, privcount/protocol.py, test/run_test.sh
I am confident this code works because the unit tests are successful and produce the same results every time.
@robgjansen, I'd like a quick review if you have time, just to make sure I haven't made any mistakes.
=> Read all events

.gitignore, privcount/counter.py, privcount/data_collector.py, privcount/node.py, privcount/tally_server.py, test/config.tor.yaml, test/config.yaml, test/run_test.sh, test/torrc
Merging based on review in
https://github.com/privcount/privcount/pull/224
=> Test tor source v2

test/run_test.sh
I'll merge this straight away, because it's trivial.
=> Handle relative tor directories correctly in run_test.sh

test/run_test.sh, test/test_encryption.py, test/test_traffic_model.py
Fix to pull request #237.
This was reviewed by @robgjansen in #246, so I'll just merge it.
=> Make default directories relative to the script location

privcount/protocol.py, test/run_test.sh, test/torrc
This is a collection of minor bug fixes that work in testing.
I don't think there's any need for them to be reviewed.
=> Never output an event count

doc/PrivCountVersion.markdown, doc/TorBranch.markdown
http://semver.org
Closes #259.
=> Document how we use Semantic Versioning for our releases

README.markdown, privcount/connection.py, privcount/inject.py, privcount/log.py, privcount/node.py, privcount/protocol.py, privcount/tally_server.py, test/run_test.sh
This makes error handling better, including in the case where clients change IP address between checkins.
=> Error handling

privcount/tally_server.py
=> don't check values for nonexistent keys

privcount/plot.py
=> Add error bars to bar plots if sigmas are included in tallies file
