privcount/privcount

privcount/util.py

A single character typo that will be quite confusing if we ever use this function

Fix a util.py typo: Exit Weight is "Wee"

---

README.markdown

Also, the format of the PrivEx citation should be consistent with the new entry.
Closes #49

Add proper citation for PrivCount paper

---

privcount/protocol.py
test/run_test.sh

Twisted catches exceptions in client code, and keeps on going by default.
So the unit tests used to run forever if a privcount process failed.
Instead, make exceptions exit the process, and check for process failure.
Closes #54.

Fail privcount on exception, and stop integration test when privcount fails

---

privcount/util.py

I left an argument out of these functions in the original branch.

Fix up some typos in the min and max counter value functions

---

privcount/tally_server.py
privcount/util.py

The TS was formatting the time as if it was an absolute epoch time, rather
than the number of seconds since it saw the client.
Closes #67.

Fix TS time formatting for lost client log message

---

README.markdown
requirements-plot.txt
requirements.txt
setup.py
test/run_test.sh

This branch modifies the PrivCount requirements.txt so that the latest version of each package is installed. It adds requirements-plot.txt for the optional plot requirements.
It improves the tests by checking that the outcomes file matches the previous outcomes file.
It also makes the test script more consistent, more reliable when plot dependencies aren't installed, and less verbose when checking process statuses.
To minimise the test differences, please reinstall your venv, or upgrade to the latest versions of each dependent package. Otherwise, you will see timing-dependent differences in some of the counts.

Use latest packages in requirements, diff test results

---

privcount/data_collector.py
privcount/share_keeper.py
privcount/tally_server.py
privcount/util.py
test/config.yaml
test/run_test.sh
test/test_counters.py

Configure the noise weight for each DC at the TS.
Uses the DC fingerprints as the identifiers of the DCs.
Adds noise once the DC fingerprint is known.
Fail DC and delete counters if fingerprint is not present in TS config, or never received by DC.
Do noise weight sanity checks at the DCs and SKs. (More sanity checks to come in #27.)
Output the noise weights in the end-of-round context.
Make the end-of-round context clearer - add placeholders for deleted items.
Also fix a minor bug in the unit tests, and fix typos in some comments.

Noise weight at TS (revised)

---

.gitignore
README.markdown
privcount/data_collector.py
privcount/protocol.py
privcount/share_keeper.py
privcount/tally_server.py
privcount/util.py
test/config.yaml

PrivCount uses a HMAC-SHA256-based handshake to verify that client and server both know a shared secret key, without revealing the key on the wire.
While a HMAC is a proven cryptographic primitive, this particular construction has not been reviewed by a cryptographer, nor has this particular implementation undergone cryptographic review. It likely contains at least one bug, and any bugs might affect security.
See #117 for my notes about the protocol handshake design, and an example handshake run.
See 	62a09db for documentation on the keys created by PrivCount, including the secret handshake key.

Redesign PrivCount Handshake to use HMAC

---

privcount/data_collector.py
privcount/share_keeper.py
privcount/statistics_noise.py
privcount/tally_server.py
privcount/util.py
test/config.yaml
test/run_test.sh

The TS checks is own delay settings before starting a round, and reports any delay in its status.
DCs can also optionally enforce a delay when the noise allocation changes.
See the individual commit messages for details

SKs enforce a delay when the noise allocation changes

---

privcount/counter.py

counter.register_dynamic_counter takes a counter name and a list of events.
It checks the events are valid, and registers the counter in the counter
events table.
Closes #149.

Provide a mechanism to register counters at runtime

---

README.markdown
privcount/__init__.py
privcount/config.py
privcount/connection.py
privcount/crypto.py
privcount/data_collector.py
privcount/inject.py
privcount/node.py
privcount/protocol.py
privcount/share_keeper.py
privcount/tally_server.py
privcount/tools/privcount
test/README.markdown
test/config.yaml
test/run_test.sh
test/test_counter.py
test/test_encryption.py
test/test_tor_ctl_event.py

Allow PrivCount data collectors to connect over a control socket or a control port, depending on their config.

Control socket

---

privcount/connection.py
privcount/inject.py
privcount/protocol.py
test/README.markdown
test/run_test.sh
test/test_tor_ctl_event.py

The injector would fill the output buffer without giving the twisted event loop time to send it.
It would also drop the last event line, failing to send it to the client.
Needed for #19.
Summary issue is #154.

Fix injector so it works without --simulate

---

privcount/connection.py
privcount/crypto.py
privcount/data_collector.py
privcount/inject.py
privcount/node.py
privcount/protocol.py
privcount/tally_server.py
test/config.yaml
test/run_test.sh
test/test_tor_ctl_event.py

This allows relay operators to set a password:
* tor: HashedControlPassword 
* PrivCount: control_password
or cookie file:
* tor: CookieAuthentication
* PrivCount: no config required
and have PrivCount securely authenticate to the control port / socket.

Implement Control Port Password and Safe Cookie authentication

---

README.markdown
doc/PrivCountAuthentication.markdown
doc/TorControlAuthentication.markdown
privcount/inject.py
privcount/protocol.py
test/config.yaml
test/run_test.sh

Make password security better by specifying the password in a separate file, not on the command-line or in a config file.
Document Tor Control Port authentication in doc/TorControlAuthentication.markdown, including Socket vs IP Port, and Cookie and Password authentication.
Document PrivCount authentication in doc/PrivCountAuthentication.markdown, including SSL, PrivCount handshake, and blinding share encryption.

Fix password security, and document PrivCount security

---

test/run_test.sh

Since #172, we use password and cookie authentication, so we don't need to
hide the "no authentication" warning any more.
Closes #183

Show the NULL authentication warning (if it appears)

---

doc/PrivCountAuthentication.markdown
doc/TorControlAuthentication.markdown

This now looks good on GitHub, merging without a review.

Fix markdown formatting in Authentication docs

---

doc/TorEvents.markdown
doc/TorNetworkOverhead.markdown

Explain which tor relay roles have access to particular kinds of data
(like streams, cells, and other info).
List and describe some tor network overheads.
Part of #191.

Document different tor roles and tor network overhead

---

.gitignore
privcount/connection.py
privcount/share_keeper.py
test/config.chutney.yaml
test/run_test.sh

Launch a chutney network with a data collector for each relay using:
`./test/run_test.sh -I . -x -s chutney`
As I remove overheads from the counters (such as #230), the diffs between chutney rounds will decrease. (But it's unlikely that I will remove them all, because not all positions can detect all overheads.)

Add a chutney source to the integration tests

---

doc/TorEvents.markdown

We now document which available data we collect, and which we exclude.
@robgjansen, please check that this is what you expect.
(I think we should do any fixes in future releases.)
Remove references to bugs #189, #190, #191, #195, #199, and update the text
to match. The tor changes are in privcount/tor#4.

Update PrivCount documentation based on tor bug fixes

---

privcount/statistics_noise.py
requirements.txt

Obsoletes #500 
This allows us to run privcount using pypy, which otherwise fails because of the scipy dependency.

removing scipy dependency by replacing scip normal cdf with math
